Release
kontur-edu/brs-extensions pull request #1
Opened 2020-12-29 12:26 UTC by Kamikoto-sama

2021-01-20 08:37 UTC, disturm requested changes
Критичные замечания только в WorkerDialog. Их лучше исправить сразу, влить в master и сделать deploy. Остальное можно править уже в master.

2021-01-20 08:37 UTC, disturm commented on src/apis/brsApi.ts
>  export enum StudentFailure {
Странно, что StudentFailure и TermType находятся вверху, а остальные типы - внизу файла.
Кажется надо сделать как-то в едином стиле. Может быть все типы на export поднять вверх? Либо все типы опустить вниз.

2021-01-20 08:37 UTC, disturm commented on src/apis/brsAuth.ts
> +            this.loadLoginInfo();
Более предпочтительна стратегия, когда есть метод tryLoadLoginInfo, а кидающий исключение метод использует его. Тогда никаких try - catch не будет. Чем меньше try - catch - тем лучше. Намеренеия надо выражать явно, а не через исключения.

2021-01-20 08:37 UTC, disturm commented on src/apis/brsAuth.ts
> +        const cookies = response.headers['x-set-cookie'] as string;
rename, название cookiES неуместно

2021-01-20 08:37 UTC, disturm commented on src/apis/brsAuth.ts
> +    async getSid(login: string, password: string) {
Название getSid намекает, что sid появится быстро, откуда-нибудь из оперативки. Ведь это же "Get"
Так что как минимум getSidAsync, лучше readSidAsycn.
Но если совсем правильно, то это действие называется login, поэтому loginAsync (да, я заметил, что login - это у тебя свойство).

2021-01-20 08:37 UTC, disturm commented on src/apis/brsAuth.ts
> +    private loadLoginInfo() {
Можно было назвать метод чуть подробнее loadLoginInfoFromCache, тогда в вызовах более понятно что к чему.

2021-01-20 08:37 UTC, disturm commented on src/apis/brsUrlProvider.ts
> +    private readonly corsProxy = 'https://kamikoto-cors-proxy.herokuapp.com';
можно было сделать константами вне класса

2021-01-20 08:37 UTC, disturm commented on src/apis/brsUrlProvider.ts
> +}
Как это же можно было написать в более "функциональном" стиле:
```
const BRS_URL = 'https://brs.urfu.ru/mrd';
const CORS_PROXY = 'https://kamikoto-cors-proxy.herokuapp.com';

interface BrsUrlProvider {
    (): string;
}

function createBrsBaseUrlProvider(withProxy: boolean) : BrsUrlProvider {
    return withProxy ? () => CORS_PROXY : () => BRS_URL;
}
```

Это не значит, что так надо переписать. Это просто, чтобы ты понимал.

2021-01-20 08:37 UTC, disturm commented on src/apis/fileApi.ts
>  export function readFromCsv(
Это API, т.е. вообще весь файл можно снести. Он не будет использоваться в приложении.

2021-01-20 08:37 UTC, disturm commented on src/apis/googleApi.ts
> +export async function authorizeAsync() {
Эта функция больше ничего не делает. Можно удалить здесь и в местах "использования"

2021-01-20 08:37 UTC, disturm commented on src/apis/googleApi.ts
> +    ) => void;
Поправь здесь `void` на  `Promise<any>`. Так будет правильно. В исходных скриптах я сам поправлю.

2021-01-20 08:37 UTC, disturm commented on src/apis/googleApi.ts
> +    ) => void;
Поправь здесь `void` на  `Promise<any>`. Так будет правильно. В исходных скриптах я сам поправлю.

2021-01-20 08:37 UTC, disturm commented on src/apis/googleAuth.ts
> +let onErrorEvent: (error: any) => void;
Прекрасно, что эти функции есть, но вообще-то надо дать возможность их как-то передавать. Либо в конструкторе, либо добавлением слушателей (как у тебя с логированием сделано).

2021-01-20 08:37 UTC, disturm commented on src/apis/googleAuth.ts
> +        await new Promise(res => {
Лучше `res` переименовать в `resolve`, а то иначе могут быть неверные ассоциации на `result` и `response`

2021-01-20 08:37 UTC, disturm commented on src/apis/googleAuth.ts
> +        await new Promise(res => {
Предполагаю, что здесь можно обойтись без async/await, а просто вернуть Promise
```
return new Promise<void>(resolve => {
}
```

2021-01-20 08:37 UTC, disturm commented on src/apis/googleAuth.ts
> +                }).then(() => {
Смешение стилей. Думаю надо либо все в рамках тела этой функции сделать с async/await, либо все с then и тогда функция уже не будет async

2021-01-20 08:37 UTC, disturm commented on src/apis/googleAuth.ts
> +    checkAuth() {
Можно написать чуть более развернуто для лучшего понимания: `checkAuthorized`

2021-01-20 08:37 UTC, disturm commented on src/components/CustomAlert.tsx
> +function Alert(props: AlertProps) {
возможно вкусовщина, но приватный компонент я бы поставил вниз после титульного компонента, ведь именно с `CustomAlert` стоит начать чтение

2021-01-20 08:37 UTC, disturm commented on src/components/CustomAlert.tsx
> +function Alert(props: AlertProps) {
Это замечание относится и к другим  файлам tsx

2021-01-20 08:37 UTC, disturm commented on src/components/NestedList.tsx
> +    return (
Код ниже громоздкий, даже читать не хочется. Кофе что-ли сделать? ☕
Надо разбить на несколько вычислений или функций

2021-01-20 08:37 UTC, disturm commented on src/components/NestedList.tsx
> +                {item.nestedItems?.length && (open ? <ExpandLess/> : <ExpandMore/>) || undefined}
`|| undefined` можно не писать, т.к. `false` тоже не отображается (не отображаются `false`, `null`, `undefined`, а вот `0` отображается)

2021-01-20 08:37 UTC, disturm commented on src/components/NestedList.tsx
> +                item.nestedItems?.length &&
`item.nestedItems?.length` - так писать нельзя, потому что React покажет `0`, если элементов в массиве нет, а сам массив есть.
Но если элементов нет, то и map вернет пустой массив. Так что правильная проверка (ты меня проверь) заключается в простом использовании оператора ?. и map: `item.nestedItems?.map`

2021-01-20 08:37 UTC, disturm commented on src/components/NestedList.tsx
> +    return (
Сейчас конструкция выглядит громоздко.
Предлагаю построение items сделать до return и положить в переменную, либо выделить в еще одну промежуточную функцию.
ListSubheader тоже можно было бы посчитать в переменную

2021-01-20 08:37 UTC, disturm commented on src/components/NestedList.tsx
> +export interface NestedListItem {
имя уже используется, возможно этот интерфейс не нужен?

2021-01-20 08:37 UTC, disturm commented on src/components/SubmitWithLoading.tsx
> +export default function SubmitWithLoading(props: Props) {
Можно перенести в файл components/SubmitWithLoading/index.js
А затем перенести внутрь папки SubmitWithLoading файл со стилями
import продолжить работать без изменений, компонент будет красиво оформлен в виде папки,
а стили можно будет импортировать для всех таких компонентов аналогично import './styles.css';
т.е. не придумывать каждый раз новое название для файла.

2021-01-20 08:37 UTC, disturm commented on src/components/SubmitWithLoading.tsx
> +export default function SubmitWithLoading(props: Props) {
То же самое можно сделать и с другими компонентами React.

2021-01-20 08:37 UTC, disturm commented on src/functions/MarksManager.ts
> +import {MarksData} from "./buildMarksAutoAsync";
MarksData должен определяться в MarksManager, аналогично типам ControlActionConfig, DisciplineConfig buildMarksAutoAsync является надстройкой над MarksManager. Вот пусть в MarksManager все типы и определяются. А иначе ощущение, что типы определены там, где придется.

2021-01-20 08:37 UTC, disturm commented on src/functions/MarksManager.ts
> +export default class MarksManager {
MarksManager немного не вписывается в папку functions. Возможно надо переименовать папку.

2021-01-20 08:37 UTC, disturm commented on src/functions/buildMarksAutoAsync.ts
> +import {ControlActionConfig, DisciplineConfig, PutMarksOptions,} from "./MarksManager";
PutMarksOptions здесь не нужен

2021-01-20 08:37 UTC, disturm commented on src/functions/buildMarksAutoAsync.ts
> +} from "./MarksManager";
кажется и без этого должно работать, ведь типы импортируются выше

2021-01-20 08:37 UTC, disturm commented on src/helpers/cache.ts
> +    return fileData as T;
Тут начинают путаться понятия localCache, localStorage, localData и fileData. Видимо надо заново продумать названия. Например, memoryCache, localStorage, memoryData и localData.

2021-01-20 08:37 UTC, disturm commented on src/loginPage/LoginPage.tsx
> +import {Grid} from "@material-ui/core";
В импортах стоит стараться поддерживать порядок. Например, все UI-компоненты из библиотеки Material UI импортировать вместе.

2021-01-20 08:37 UTC, disturm commented on src/loginPage/LoginPage.tsx
> +import {Grid} from "@material-ui/core";
Посмотри, может быть еще где-то есть.

2021-01-20 08:37 UTC, disturm commented on src/loginPage/LoginPage.tsx
> +    handleFieldChanged(e: React.ChangeEvent<HTMLInputElement>) {
Вместо всей этой мути в bind для обработчиков в новейшем JS можно писать так:
```
handleFieldChanged = (e: React.ChangeEvent<HTMLInputElement>) => {
    const field = e.target
    this.credentials[field.id] = field.value
}
```

Эта запись означает, что при создании каждого объекта ему будет добавлено свойство `handleFieldChanged`,
в котором будет лежать стрелочная функций. Такая функция, как известно, берет `this` из контекста определения, т.е. это будет объект.
Сейчас же `handleFieldChanged(e)` функция добавляется в `prototype` объекта и это именно функция, которая берет `this` из контекста вызова.
Может показаться, что запись текущая запись `handleFieldChanged(e)` выгоднее, т.к. функция создается только один раз, но это не так, ведь в нашем случае все равно приходится использовать `bind`, а `bind` всегда создает новую функцию.

2021-01-20 08:37 UTC, disturm commented on src/loginPage/LoginPage.tsx
> +                alertMessage: 'Неверные имя пользователя или пароль',
сообщение может врать, т.к. еще могут быть проблемы с proxy.

2021-01-20 08:37 UTC, disturm commented on src/loginPage/LoginPage.tsx
> +    async loginBrs() {
`loginBrsAsync`

2021-01-20 08:37 UTC, disturm commented on src/workPage/DisciplinesFetch.tsx
> +const useStyles = makeStyles(() =>
Обычно use в React используется для хуков. А это значит, что надо стараться не использовать его для еще чего-то.

2021-01-20 08:37 UTC, disturm commented on src/workPage/DisciplinesFetch.tsx
> +const useStyles = makeStyles(() =>
Аналогичные с useStyles есть и в других компонентах

2021-01-20 08:37 UTC, disturm commented on src/workPage/DisciplinesFetch.tsx
> +function DisciplinesFetch(props: Props) {
Кажется этот компонент слишком жирный.
Думаю, что стоит выделить в отдельную функцию-компонент хотя бы контролы-выпадашки
Также предлагаю вытащить функции, которые можно из DisciplinesFetch. Если при этом понадобится передать 1-2 лишних параметра - это нормально.

2021-01-20 08:37 UTC, disturm commented on src/workPage/DisciplinesFetch.tsx
> +    let isModule = false;
Довольно странно, что это не state.
Пока вроде бы работает, но как в такой схеме задать значение элемента по умолчанию и учитывать его даже если пользователь ничего не поменал?

2021-01-20 08:37 UTC, disturm commented on src/workPage/DisciplinesFetch.tsx
> +    const [disciplines, setDisciplines] = React.useState(disciplinesEmpty);
Рекомендуется хуки размещать в самом верху компонента, т.к. они определяют его поведения.
Конечно, когда у тебя локальные переменные сверху уедут в отдельный компонент, то все станет ок. Но пока хуки низковато.

2021-01-20 08:37 UTC, disturm commented on src/workPage/DisciplinesFetch.tsx
> +            <br/>
Вместо <br/> лучше использовать padding или margin. Короче, CSS )

2021-01-20 08:37 UTC, disturm commented on src/workPage/SpreadsheetFetch.tsx
> +    tableUrl = '';
странно, что это не в state

2021-01-20 08:37 UTC, disturm commented on src/workPage/SpreadsheetFetch.tsx
> +            const res = await gapi.client.sheets.spreadsheets.get({spreadsheetId});
почему здесь используется gapi напрямую, а не googleApi.ts?

2021-01-20 08:37 UTC, disturm commented on src/workPage/UnauthorizedAlert.tsx
> +        cache.clear('loginInfo');
Это как-то некрасиво cache.clear('loginInfo');
Во-первых, для управления аутентификацией есть отдельные менеджеры, так что надо использовать их, а не что-то низкоуровневое.
Во-вторых, использовать глобальные переменные в компонентах - этот так себе идея. Это слишком неявно.
Есть же React.Context и props

2021-01-20 08:37 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +    }
А где же componentWillUnmount, который будет отменять процесс при закрытии диалога?

2021-01-20 08:37 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +        this.setState({cancelPending: true});
Видимо в этот момент также должна происходит отписка от логгера?
Точнее сразу после того, как cancel успешно отработает.
Это означает, что marksManager.cancel должен стать marksManager.cancelAsync,
а this.setState лучше выполнить до запуска cancel

2021-01-20 08:37 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +                            ))}
Наконец-то я нашел код, из-за которого лог читать невозможно!
Надо использовать просто текст! А когда-нибудь потом — MarkDown.
И еще стоит сделать диалоговое окно побольше, чтобы больше влезало.

2021-01-20 08:37 UTC, disturm commented on src/workPage/WorkPage.tsx
> +            this.handleUnauthorized();
лучше, конечно, говорить конкретно какая сессия протухла, раз это возможно.

2021-01-20 08:37 UTC, disturm commented on src/workPage/WorkPage.tsx
> +                        </Collapse>
Для стоит выделить отдельную функцию,
тогда в render будет лучше видна структура страницы

2021-01-21 07:54 UTC, Kamikoto-sama commented on src/workPage/WorkerDialog.tsx
> +    }
Закрыть диалог, не завершив процесс, возможно только, если перезагрузить страницу, но тогда и процесс завершится. Потому что кнопка для его закрытия появляется только после завершения процесса.

2021-01-21 07:59 UTC, Kamikoto-sama commented on src/workPage/WorkerDialog.tsx
> +        this.setState({cancelPending: true});
На счет отписки не думаю, потому что кнопка cancel именно, что начинает pending, а не сразу завершает процесс. То есть он может еще что-то доделывать и печатать в лог. Думаю, что, если отписываться от логгера, то после завершения процесса.

2021-01-21 08:01 UTC, Kamikoto-sama commented on src/workPage/WorkerDialog.tsx
> +                            ))}
Просто текст в смысле просто textarea ?

2021-01-21 14:11 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +    }
Или если React захочет перерисовать родителя вместе с детьми. Даже если сейчас это не дыра, то не стоит ее оставлять.

2021-01-21 14:13 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +        this.setState({cancelPending: true});
Согласен. Слишком рано отписывать не надо. Действительно простое решение не работает.

2021-01-21 14:13 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +                            ))}
Да!

2021-01-21 14:14 UTC, disturm commented on src/workPage/WorkerDialog.tsx
> +                            ))}
Но лучше просто печатный текст с прокруткой. textarea еще позволяет редактировать, а это здесь лишнее.

2021-01-23 13:16 UTC, Kamikoto-sama commented on src/workPage/WorkerDialog.tsx
> +        this.setState({cancelPending: true});
Добавил отписку от логгера.

2021-01-23 14:25 UTC, merged

2021-01-23 17:25 UTC, Kamikoto-sama commented on src/apis/brsApi.ts
>  export enum StudentFailure {
Исправил

2021-01-23 17:40 UTC, Kamikoto-sama commented on src/apis/brsAuth.ts
> +            this.loadLoginInfo();
Исправил

2021-01-23 17:44 UTC, Kamikoto-sama commented on src/apis/brsAuth.ts
> +    private loadLoginInfo() {
Исправил

2021-01-23 17:46 UTC, Kamikoto-sama commented on src/apis/brsUrlProvider.ts
> +    private readonly corsProxy = 'https://kamikoto-cors-proxy.herokuapp.com';
Исправил

2021-01-23 17:47 UTC, Kamikoto-sama commented on src/apis/brsUrlProvider.ts
> +}
Понял

2021-01-23 17:48 UTC, Kamikoto-sama commented on src/apis/fileApi.ts
>  export function readFromCsv(
Удалил

2021-01-23 17:51 UTC, Kamikoto-sama commented on src/apis/googleApi.ts
> +export async function authorizeAsync() {
Удалил

2021-01-23 17:54 UTC, Kamikoto-sama commented on src/apis/googleAuth.ts
> +let onErrorEvent: (error: any) => void;
Они уже не нужны. Убрал

2021-01-23 17:56 UTC, Kamikoto-sama commented on src/apis/googleAuth.ts
> +        await new Promise(res => {
Исправил

2021-01-23 17:56 UTC, Kamikoto-sama commented on src/apis/googleAuth.ts
> +        await new Promise(res => {
Исправил

2021-01-28 12:20 UTC, Kamikoto-sama commented on src/apis/brsAuth.ts
> +        const cookies = response.headers['x-set-cookie'] as string;
Исправил

2021-01-28 12:24 UTC, Kamikoto-sama commented on src/apis/brsAuth.ts
> +    async getSid(login: string, password: string) {
Исправил

2021-01-28 12:25 UTC, Kamikoto-sama commented on src/apis/googleApi.ts
> +    ) => void;
Исправлено

2021-01-28 12:26 UTC, Kamikoto-sama commented on src/apis/googleApi.ts
> +    ) => void;
Исправлено

2021-01-28 12:38 UTC, Kamikoto-sama commented on src/apis/googleAuth.ts
> +    checkAuth() {
Исправил

2021-01-28 12:40 UTC, Kamikoto-sama commented on src/components/CustomAlert.tsx
> +function Alert(props: AlertProps) {
Так было изначально в примере на MUI. Исправил

2021-01-28 12:55 UTC, Kamikoto-sama commented on src/components/NestedList.tsx
> +    return (
Исправил

2021-01-28 13:01 UTC, Kamikoto-sama commented on src/components/NestedList.tsx
> +                item.nestedItems?.length &&
Исправил

2021-01-28 13:51 UTC, Kamikoto-sama commented on src/components/NestedList.tsx
> +                {item.nestedItems?.length && (open ? <ExpandLess/> : <ExpandMore/>) || undefined}
Исправил

2021-01-28 13:51 UTC, Kamikoto-sama commented on src/components/NestedList.tsx
> +    return (
Исправил

2021-01-28 13:51 UTC, Kamikoto-sama commented on src/components/NestedList.tsx
> +export interface NestedListItem {
Исправил

2021-01-30 12:58 UTC, Kamikoto-sama commented on src/components/SubmitWithLoading.tsx
> +export default function SubmitWithLoading(props: Props) {
Исправил

2021-01-30 13:11 UTC, Kamikoto-sama commented on src/functions/MarksManager.ts
> +import {MarksData} from "./buildMarksAutoAsync";
Исправлено

2021-01-30 13:14 UTC, Kamikoto-sama commented on src/functions/MarksManager.ts
> +export default class MarksManager {
Исправил

2021-01-30 13:16 UTC, Kamikoto-sama commented on src/functions/buildMarksAutoAsync.ts
> +import {ControlActionConfig, DisciplineConfig, PutMarksOptions,} from "./MarksManager";
Исправилено

2021-01-30 13:18 UTC, Kamikoto-sama commented on src/functions/buildMarksAutoAsync.ts
> +} from "./MarksManager";
Исправлено

2021-01-30 13:43 UTC, Kamikoto-sama commented on src/helpers/cache.ts
> +    return fileData as T;
Исправил

2021-01-30 14:16 UTC, Kamikoto-sama commented on src/loginPage/LoginPage.tsx
> +import {Grid} from "@material-ui/core";
Исправил

2021-01-30 14:26 UTC, Kamikoto-sama commented on src/loginPage/LoginPage.tsx
> +    handleFieldChanged(e: React.ChangeEvent<HTMLInputElement>) {
Исправил

2021-01-30 14:34 UTC, Kamikoto-sama commented on src/loginPage/LoginPage.tsx
> +    async loginBrs() {
Исправил

2021-02-01 11:55 UTC, Kamikoto-sama commented on src/workPage/DisciplinesFetch.tsx
> +const useStyles = makeStyles(() =>
Это хук

2021-02-05 13:08 UTC, Kamikoto-sama commented on src/workPage/DisciplinesFetch.tsx
> +    const [disciplines, setDisciplines] = React.useState(disciplinesEmpty);
Исправил

2021-02-05 13:14 UTC, Kamikoto-sama commented on src/workPage/DisciplinesFetch.tsx
> +            <br/>
Исправил

2021-02-05 13:33 UTC, Kamikoto-sama commented on src/workPage/SpreadsheetFetch.tsx
> +            const res = await gapi.client.sheets.spreadsheets.get({spreadsheetId});
Исправил

2021-02-06 13:28 UTC, Kamikoto-sama commented on src/workPage/DisciplinesFetch.tsx
> +function DisciplinesFetch(props: Props) {
Исправил

2021-02-11 13:07 UTC, Kamikoto-sama commented on src/workPage/WorkerDialog.tsx
> +                            ))}
Передумали

2021-02-11 13:27 UTC, Kamikoto-sama commented on src/apis/googleAuth.ts
> +                }).then(() => {
Переделал

2021-02-11 14:19 UTC, Kamikoto-sama commented on src/workPage/DisciplinesFetch.tsx
> +    let isModule = false;
Исправил

2021-02-11 14:19 UTC, Kamikoto-sama commented on src/workPage/SpreadsheetFetch.tsx
> +    tableUrl = '';
Исправил

2021-02-11 14:19 UTC, Kamikoto-sama commented on src/workPage/UnauthorizedAlert.tsx
> +        cache.clear('loginInfo');
Исправил

2021-02-11 14:20 UTC, Kamikoto-sama commented on src/workPage/WorkerDialog.tsx
> +    }
Исправил

2021-02-12 08:40 UTC, Kamikoto-sama commented on src/workPage/WorkPage.tsx
> +                        </Collapse>
Исправил

2021-02-12 08:52 UTC, Kamikoto-sama commented on src/workPage/WorkPage.tsx
> +            this.handleUnauthorized();
Исправил

2021-02-12 09:35 UTC, Kamikoto-sama commented on src/loginPage/LoginPage.tsx
> +                alertMessage: 'Неверные имя пользователя или пароль',
Исправил